# Generated by Django 5.1.2 on 2025-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_course_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_student',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
